---

- name: ensure the wordpress database exists
  mysql_db: name={{ wp_db_name }} state=present login_user={{ wp_db_user }} login_password={{ wp_db_pass }}

- name: check if wordpress is installed
  shell: wp core is-installed --path="{{ wp_web_root }}"
  register: is_installed
  ignore_errors: yes
  changed_when: no
  tags:
    - install

- name: install wordpress
  command: wp core install --path="{{ wp_web_root }}" --url="{{ wp_site_url }}" --title="{{ wp_site_title }}" --admin_user="{{ wp_site_user }}" --admin_password="{{ wp_site_pass }}" --admin_email="{{ wp_site_email }}"
  when: is_installed.rc == 1
  tags:
    - install
