---

- block:

  - name: download wordpress
    command: wp core download --path="{{ wp_web_root }}" --allow-root
    args:
      creates: "{{ wp_web_root }}/wp-admin"

  - name: write wp-config.php
    command: wp core config --path="{{ wp_web_root }}" --dbname="{{ wp_db_name }}" --dbuser="{{ wp_db_user }}" --dbpass="{{ wp_db_pass }}" --allow-root
    args:
      creates: "{{ wp_web_root }}/wp-config.php"

  when: wp_web_import is not defined

- name: set directory to apache user and writable
  file: path="{{ wp_web_root }}" state=directory recurse=yes owner="{{ wp_web_user }}" group="{{ wp_web_group }}" mode=0774
  when: wp_web_writable == "yes"
  become: true
