---

- name: install php
  package: name={{ item }} state=present
  with_items:
    - php5
    - php5-mysql
  become: true
  tags:
    - prepare

- name: make wordpress path writable
  file: path="{{ wp_web_root }}" mode=0777 recurse=yes
  become: true

- name: download wordpress
  command: wp core download --path="{{ wp_web_root }}"
  args:
    creates: "{{ wp_web_root }}/wp-admin"
  tags:
    - prepare

- name: write wp-config.php
  command: wp core config --path="{{ wp_web_root }}" --dbname="{{ wp_db_name }}" --dbuser="{{ wp_db_user }}" --dbpass="{{ wp_db_pass }}"
  args:
    creates: "{{ wp_web_root }}/wp-config.php"
  tags:
    - configure

- name: set owner of wordpress dir to apache user
  file: path="{{ wp_web_root }}" state=directory recurse=yes owner="{{ wp_web_user }}" group="{{ wp_web_group }}"
  become: true
  tags:
    - configure
