---

- name: install php
  package: name={{ item }} state=present
  with_items:
    - php5
    - php5-mysql
  become: true
  tags:
    - prepare

- name: make web root writable
  file: path="{{ wp.web.root }}" mode=0777 recurse=yes
  become: true

- name: download wordpress
  command: wp core download --path="{{ wp.web.root }}"
  args:
    creates: "{{ wp.web.root }}/wp-admin"
  tags:
    - prepare

- name: configure wordpress
  command: wp core config --path="{{ wp.web.root }}" --dbname={{ wp.db.name }} --dbuser={{ wp.db.user }} --dbpass={{ wp.db.pass }}
  args:
    creates: "{{ wp.web.root }}/wp-config.php"
  tags:
    - configure

- name: set owner to apache
  file: path="{{ wp.web.root }}" state=directory recurse=yes owner="{{ wp.web.user }}" group="{{ wp.web.group }}"
  become: true
  tags:
    - configure

- name: ensure the wordpress database exists
  mysql_db: name={{ wp.db.name }} state=present login_user={{ wp.db.user }} login_password={{ wp.db.pass }}

- name: check if wordpress is installed
  shell: wp core is-installed --path="{{ wp.web.root }}"
  register: is_installed
  changed_when: no
  tags:
    - install

- name: install wordpress
  command: wp core install --path="{{ wp.web.root }}" --url={{ wp.site.url }} --title={{ wp.site.title }} --admin_user={{ wp.site.user }} --admin_password={{ wp.site.pass }} --admin_email={{ wp.site.email }}
  when: is_installed.rc == 1
  tags:
    - install
